#include <chrono>
#include <cstdio>
#include <iostream>
#include <opencv2/opencv.hpp>

#include "CameraStream.hpp"
#include "DesktopUI.hpp"
#include "StereoService.hpp"

// ── Camera stream URLs ────────────────────────────────────────────────────────
static constexpr char CAM_LEFT_URL[]  = "http://192.168.0.118:81/stream";
static constexpr char CAM_RIGHT_URL[] = "http://192.168.0.117:81/stream";

// Path to the YAML generated by calibration/calibration.py
static constexpr char CALIB_YAML[] = "calibration/parametros_estereo.yml";

// Maximum timestamp difference (ms) to accept a stereo pair as synchronised
static constexpr int SYNC_THRESHOLD_MS = 50;

// ─────────────────────────────────────────────────────────────────────────────

int main() {
    CameraStream  camL(CAM_LEFT_URL,  0);
    CameraStream  camR(CAM_RIGHT_URL, 1);
    StereoService stereo(CALIB_YAML);

    camL.start();
    camR.start();

    cv::Mat frameL, frameR;
    std::chrono::steady_clock::time_point tsL, tsR;

    cv::Mat dispColor;
    float   distanceCm = 0.0f;

    // FPS counter
    cv::TickMeter fpsTimer;
    int           frameCount = 0;
    double        fpsVal     = 0.0;

    std::cout << "Stereo vision running. Press ESC or 'q' to quit.\n";

    while (true) {
        bool newL = camL.getFrame(frameL, tsL);
        bool newR = camR.getFrame(frameR, tsR);

        if (newL && newR && !frameL.empty() && !frameR.empty()) {

            // Soft synchronisation: discard pairs too far apart in time
            auto diffMs = std::abs(
                std::chrono::duration_cast<std::chrono::milliseconds>(tsL - tsR).count());
            if (diffMs > SYNC_THRESHOLD_MS) {
                cv::waitKey(1);
                continue;
            }

            // ── Rectification ────────────────────────────────────────────────
            cv::Mat leftRect  = stereo.isCalibrated() ? stereo.rectifyLeft(frameL)  : frameL;
            cv::Mat rightRect = stereo.isCalibrated() ? stereo.rectifyRight(frameR) : frameR;

            // ── Disparity ────────────────────────────────────────────────────
            if (stereo.isCalibrated()) {
                cv::Mat leftGray, rightGray;
                cv::cvtColor(leftRect,  leftGray,  cv::COLOR_BGR2GRAY);
                cv::cvtColor(rightRect, rightGray, cv::COLOR_BGR2GRAY);

                cv::Mat dispRaw = stereo.process(leftGray, rightGray);

                // Normalize disparity for colour display
                cv::Mat dispNorm;
                cv::normalize(dispRaw, dispNorm, 0, 255, cv::NORM_MINMAX, CV_8U);
                cv::applyColorMap(dispNorm, dispColor, cv::COLORMAP_INFERNO);

                // ── Depth at image centre ────────────────────────────────────
                cv::Mat disp32F;
                dispRaw.convertTo(disp32F, CV_32F, 1.0 / 16.0);  // SGBM stores ×16
                cv::Mat pts3D;
                cv::reprojectImageTo3D(disp32F, pts3D, stereo.getQ(), true);

                cv::Point3f c = pts3D.at<cv::Point3f>(leftGray.rows / 2,
                                                       leftGray.cols / 2);
                // Calibration in mm → divide by 10 for cm; reject outliers
                if (c.z > 10.0f && c.z < 10000.0f)
                    distanceCm = c.z / 10.0f;
            }

            // ── FPS ──────────────────────────────────────────────────────────
            fpsTimer.start();
            if (++frameCount % 30 == 0) {
                fpsTimer.stop();
                fpsVal = 30.0 / fpsTimer.getTimeSec();
                fpsTimer.reset();
                char buf[32];
                std::snprintf(buf, sizeof(buf), "FPS: %.1f", fpsVal);
                std::cout << buf << "\n";
            }

            // Overlay FPS on the left panel
            char fpsBuf[32];
            std::snprintf(fpsBuf, sizeof(fpsBuf), "%.0f fps", fpsVal);
            cv::putText(leftRect, fpsBuf,
                        cv::Point(8, leftRect.rows - 8),
                        cv::FONT_HERSHEY_SIMPLEX, 0.5,
                        cv::Scalar(0, 255, 0), 1);

            // ── GUI ──────────────────────────────────────────────────────────
            const cv::Mat& dispPanel = dispColor.empty() ? leftRect : dispColor;
            DesktopUI::renderMainWindow(leftRect, rightRect, dispPanel);
            DesktopUI::renderOutputWindow(leftRect, distanceCm);
        }

        int key = cv::waitKey(1);
        if (key == 27 || key == 'q') break;
    }

    camL.stop();
    camR.stop();
    cv::destroyAllWindows();
    return 0;
}
